alias d-run='docker run -it --rm'
alias d-run-bash='docker run -it --rm --entrypoint=/bin/bash'
alias psa='ps -aux | grep'
alias d-im='docker images |grep'
alias del='trash-put'
alias c-dir='rm -rf ./*' 
alias re='rebar3'
alias re-bash='source ~/.bashrc'
alias re-tmux='tmux source-file ~/.tmux.conf'
alias is-ok='echo $?'
alias s-new='subl -n -a .'
alias t='python ~/0_workDir/1_Intall/t/t.py --task-dir ~/tasks --list tasks'
alias l='ls -gAh --group-directories-first'

